pupradar_capture: pupradar::UsbDevice Class Reference
pupradar::UsbDevice Class Reference final
#include <UsbDevice.hpp>
Public Member Functions
UsbDevice ()
Initialises the libusb-1.0 context.
~UsbDevice () override
Releases the USB interface (if claimed), closes the device handle, and exits the libusb context.
UsbDevice (const UsbDevice &)=delete
UsbDevice & operator= (const UsbDevice &)=delete
void open (std::uint16_t vid, std::uint16_t pid) override
Opens the USB device identified by vid / pid.
void close () override
Releases the currently claimed interface and closes the device handle.
bool isOpen () const override
Returns whether a device handle is currently held open.
void claimInterface (int interface_number) override
Claims a USB interface, detaching any kernel driver that holds it.
void setAltSetting (int interface_number, int alt_setting) override
Selects an alternate setting for the specified USB interface.
std::size_t controlTransfer (std::uint8_t bm_request_type, std::uint8_t b_request, std::uint16_t w_value, std::uint16_t w_index, std::uint8_t *data, std::size_t length, unsigned int timeout_ms) override
Issues a USB control transfer (IN or OUT, depending on bm).
std::size_t bulkWrite (std::uint8_t endpoint, const std::uint8_t *data, std::size_t length, unsigned int timeout_ms) override
Performs a synchronous USB bulk OUT (host-to-device) transfer.
std::size_t bulkRead (std::uint8_t endpoint, std::uint8_t *data, std::size_t length, unsigned int timeout_ms) override
Performs a synchronous USB bulk IN (device-to-host) transfer.
void reopenAfterRenumeration (const VidPid *candidates, std::size_t num_candidates, unsigned int timeout_ms) override
Polls for the device to reappear after a firmware-triggered re-enumeration.
Public Member Functions inherited from pupradar::IUsbBackend
virtual ~IUsbBackend ()=default
Private Attributes
libusb_context * ctx_ = nullptr
libusb_device_handle * handle_ = nullptr
int claimed_iface_ = -1
Detailed Description
Definition at line 11 of file UsbDevice.hpp.
Constructor & Destructor Documentation
UsbDevice() [1/2]
pupradar::UsbDevice::UsbDevice ()
Initialises the libusb-1.0 context.
Exceptions
UsbError if libusb_init fails.
Definition at line 92 of file UsbDevice.cpp.
References ctx_.
Referenced by operator=(), and UsbDevice().
~UsbDevice()
pupradar::UsbDevice::~UsbDevice () override
Releases the USB interface (if claimed), closes the device handle, and exits the libusb context.
Definition at line 101 of file UsbDevice.cpp.
References close(), and ctx_.
UsbDevice() [2/2]
pupradar::UsbDevice::UsbDevice (const UsbDevice &) delete
References UsbDevice().
Member Function Documentation
bulkRead()
std::size_t pupradar::UsbDevice::bulkRead (std::uint8_t ep, std::uint8_t * data, std::size_t length, unsigned int timeout_ms) override virtual
Performs a synchronous USB bulk IN (device-to-host) transfer.
On LIBUSB_ERROR_TIMEOUT, any bytes received before the deadline are returned rather than raising an exception, allowing the capture loop to save partial data and retry instead of aborting the entire capture.
Parameters
ep Bulk IN endpoint address (direction bit 7 set).
data Buffer to receive data into.
length Buffer capacity in bytes.
timeout_ms Transfer timeout in milliseconds (0 = wait indefinitely).
Returns
Number of bytes received; 0 indicates a genuine timeout with no data (caller should retry).
Exceptions
UsbError if the device is not open or a non-timeout transfer error occurs.
Implements pupradar::IUsbBackend.
Definition at line 257 of file UsbDevice.cpp.
References handle_.
bulkWrite()
std::size_t pupradar::UsbDevice::bulkWrite (std::uint8_t ep, const std::uint8_t * data, std::size_t length, unsigned int timeout_ms) override virtual
Performs a synchronous USB bulk OUT (host-to-device) transfer.
Parameters
ep Bulk OUT endpoint address (direction bit 7 clear).
data Data to send.
length Number of bytes to send.
timeout_ms Transfer timeout in milliseconds (0 = wait indefinitely).
Returns
Number of bytes actually written.
Exceptions
UsbError if the device is not open or the transfer fails.
Implements pupradar::IUsbBackend.
Definition at line 228 of file UsbDevice.cpp.
References handle_.
claimInterface()
void pupradar::UsbDevice::claimInterface (int interface_number) override virtual
Claims a USB interface, detaching any kernel driver that holds it.
On Linux, usbfs refuses to claim an interface while a kernel driver (e.g. usbhid) owns it. This method detaches the driver first, then claims the interface. The interface number is stored so that close() can release it automatically.
Parameters
interface_number USB interface number (0-based).
Exceptions
UsbError if the device is not open, driver detach fails (excluding LIBUSB_ERROR_NOT_FOUND), or libusb_claim_interface fails.
Implements pupradar::IUsbBackend.
Definition at line 160 of file UsbDevice.cpp.
References claimed_iface_, and handle_.
close()
void pupradar::UsbDevice::close () override virtual
Releases the currently claimed interface and closes the device handle.
Safe to call on an already-closed device (no-op).
Implements pupradar::IUsbBackend.
Definition at line 131 of file UsbDevice.cpp.
References claimed_iface_, and handle_.
Referenced by open(), reopenAfterRenumeration(), and ~UsbDevice().
controlTransfer()
std::size_t pupradar::UsbDevice::controlTransfer (std::uint8_t bm, std::uint8_t br, std::uint16_t wv, std::uint16_t wi, std::uint8_t * data, std::size_t length, unsigned int timeout_ms) override virtual
Issues a USB control transfer (IN or OUT, depending on bm).
Parameters map directly onto the USB SETUP packet fields and are passed verbatim to libusb_control_transfer.
Parameters
bm bmRequestType — direction, type, and recipient bits.
br bRequest — the specific request code.
wv wValue field.
wi wIndex field.
data Data buffer (written by device for IN; read by device for OUT).
length Buffer size in bytes; must be ≤ 65535.
timeout_ms Transfer timeout in milliseconds (0 = wait indefinitely).
Returns
Number of bytes actually transferred.
Exceptions
UsbError if the device is not open, length exceeds 65535, or the transfer fails.
Implements pupradar::IUsbBackend.
Definition at line 203 of file UsbDevice.cpp.
References handle_.
isOpen()
bool pupradar::UsbDevice::isOpen () const override virtual
Returns whether a device handle is currently held open.
Returns
true if open, false otherwise.
Implements pupradar::IUsbBackend.
Definition at line 146 of file UsbDevice.cpp.
References handle_.
open()
void pupradar::UsbDevice::open (std::uint16_t vid, std::uint16_t pid) override virtual
Opens the USB device identified by vid / pid.
Any previously opened device is closed first. Enumerates all attached USB devices and opens the first match.
Parameters
vid USB Vendor ID.
pid USB Product ID.
Exceptions
UsbError if no matching device is found or libusb_open fails.
Implements pupradar::IUsbBackend.
Definition at line 116 of file UsbDevice.cpp.
References close(), ctx_, and handle_.
operator=()
UsbDevice & pupradar::UsbDevice::operator= (const UsbDevice &) delete
References UsbDevice().
reopenAfterRenumeration()
void pupradar::UsbDevice::reopenAfterRenumeration (const VidPid * candidates, std::size_t num_candidates, unsigned int timeout_ms) override virtual
Polls for the device to reappear after a firmware-triggered re-enumeration.
The FX3 chip disconnects and reconnects with a new USB address (and possibly a new VID:PID) after receiving the 0xA0 boot firmware. This method closes the stale handle, then polls candidates every 100 ms until one reappears or timeout_ms elapses. The post-firmware VID:PID must be included in candidates.
Parameters
candidates Array of VID:PID pairs to accept as the re-enumerated device.
num_candidates Number of entries in candidates.
timeout_ms Maximum time to wait in milliseconds.
Exceptions
UsbError if no candidate device appears within the timeout, with a diagnostic listing the currently visible USB devices.
Implements pupradar::IUsbBackend.
Definition at line 290 of file UsbDevice.cpp.
References close(), ctx_, handle_, pupradar::IUsbBackend::VidPid::pid, and pupradar::IUsbBackend::VidPid::vid.
setAltSetting()
void pupradar::UsbDevice::setAltSetting (int interface_number, int alt_setting) override virtual
Selects an alternate setting for the specified USB interface.
Parameters
interface_number USB interface number (must already be claimed).
alt_setting Alternate setting index.
Exceptions
UsbError if the device is not open or the call fails.
Implements pupradar::IUsbBackend.
Definition at line 180 of file UsbDevice.cpp.
References handle_.
Member Data Documentation
claimed_iface_
int pupradar::UsbDevice::claimed_iface_ = -1 private
Definition at line 51 of file UsbDevice.hpp.
Referenced by claimInterface(), and close().
ctx_
libusb_context* pupradar::UsbDevice::ctx_ = nullptr private
Definition at line 49 of file UsbDevice.hpp.
Referenced by open(), reopenAfterRenumeration(), UsbDevice(), and ~UsbDevice().
handle_
libusb_device_handle* pupradar::UsbDevice::handle_ = nullptr private
Definition at line 50 of file UsbDevice.hpp.
Referenced by bulkRead(), bulkWrite(), claimInterface(), close(), controlTransfer(), isOpen(), open(), reopenAfterRenumeration(), and setAltSetting().
The documentation for this class was generated from the following files:
include/pupradar/UsbDevice.hpp
src/UsbDevice.cpp