pupradar_capture: pupradar::IqWriter Class Reference
pupradar::IqWriter Class Reference
#include <IqWriter.hpp>
Public Member Functions
IqWriter (const std::string &out_basename)
~IqWriter ()
IqWriter (const IqWriter &)=delete
IqWriter & operator= (const IqWriter &)=delete
void write (const std::uint8_t *data, std::size_t length)
IqSink-compatible — feed into RadarSession::captureIq.
void finalize (const CaptureMetadata &md)
Closes the binary file (flushes), then writes the JSON sidecar.
const std::string & binPath () const
const std::string & jsonPath () const
Private Attributes
std::string bin_path_
std::string json_path_
std::ofstream bin_
Detailed Description
Definition at line 13 of file IqWriter.hpp.
Constructor & Destructor Documentation
IqWriter() [1/2]
pupradar::IqWriter::IqWriter (const std::string & out_basename) explicit
Parameters
out_basename Base path with no extension; .bin and .json are appended.
Definition at line 76 of file IqWriter.cpp.
References bin_, bin_path_, and json_path_.
Referenced by IqWriter(), and operator=().
~IqWriter()
pupradar::IqWriter::~IqWriter () default
IqWriter() [2/2]
pupradar::IqWriter::IqWriter (const IqWriter &) delete
References IqWriter().
Member Function Documentation
binPath()
const std::string & pupradar::IqWriter::binPath () const inline
Definition at line 28 of file IqWriter.hpp.
References bin_path_.
Referenced by main().
finalize()
void pupradar::IqWriter::finalize (const CaptureMetadata & md)
Closes the binary file (flushes), then writes the JSON sidecar.
Definition at line 95 of file IqWriter.cpp.
References bin_, json_path_, and pupradar::serializeMetadataJson().
Referenced by main().
jsonPath()
const std::string & pupradar::IqWriter::jsonPath () const inline
Definition at line 29 of file IqWriter.hpp.
References json_path_.
Referenced by main().
operator=()
IqWriter & pupradar::IqWriter::operator= (const IqWriter &) delete
References IqWriter().
write()
void pupradar::IqWriter::write (const std::uint8_t * data, std::size_t length)
IqSink-compatible — feed into RadarSession::captureIq.
Definition at line 87 of file IqWriter.cpp.
References bin_, and bin_path_.
Referenced by main().
Member Data Documentation
bin_
std::ofstream pupradar::IqWriter::bin_ private
Definition at line 34 of file IqWriter.hpp.
Referenced by finalize(), IqWriter(), and write().
bin_path_
std::string pupradar::IqWriter::bin_path_ private
Definition at line 32 of file IqWriter.hpp.
Referenced by binPath(), IqWriter(), and write().
json_path_
std::string pupradar::IqWriter::json_path_ private
Definition at line 33 of file IqWriter.hpp.
Referenced by finalize(), IqWriter(), and jsonPath().
The documentation for this class was generated from the following files:
include/pupradar/IqWriter.hpp
src/IqWriter.cpp