pupradar_capture: pupradar::RadarSession Class Reference
pupradar::RadarSession Class Reference
#include <RadarSession.hpp>
Public Member Functions
RadarSession (IUsbBackend &usb, std::string firmware_hex_path)
Constructs a RadarSession bound to a USB backend and a firmware image.
void initialize (const std::vector< IUsbBackend::VidPid > &post_fw_candidates, unsigned int reenum_timeout_ms=5000)
Full bring-up: enumerate (pre-firmware), claim, download firmware, wait for re-enumeration, claim again, request board info.
void configure (const CaptureConfig &cfg)
Apply a configuration: send modulation/sweep/sampling/Tx/Rx and PLL regs.
CaptureMetadata captureIq (const CaptureConfig &cfg, const IqSink &sink)
Bulk-read IQ for cfg.duration_s seconds, sinking bytes to sink.
void shutdown ()
Power-down convenience: release interfaces, close device.
const std::vector< std::uint16_t > & lastBoardInfo () const
For testing / observability.
Private Member Functions
void sendCommand (std::uint8_t opcode, std::uint8_t parameter)
Packs an opcode/parameter pair into a 512-byte bulk-OUT packet and sends it to EP2.
void downloadFirmware ()
Downloads the Intel HEX firmware image into FX3 RAM via the Cypress 0xA0 loader protocol.
void requestBoardInfo ()
Sends the 0xFA board-info request and parses the response into last_board_info_.
Private Attributes
IUsbBackend & usb_
std::string fw_path_
std::vector< std::uint16_t > last_board_info_
Detailed Description
Definition at line 54 of file RadarSession.hpp.
Constructor & Destructor Documentation
RadarSession()
pupradar::RadarSession::RadarSession (IUsbBackend & usb, std::string firmware_hex_path)
Constructs a RadarSession bound to a USB backend and a firmware image.
Parameters
usb Reference to the USB backend (lifetime must exceed this object).
firmware_hex_path Path to the FX3 firmware Intel HEX file (e.g. "SDR_USB_FW.hex").
Definition at line 62 of file RadarSession.cpp.
References fw_path_, and usb_.
Member Function Documentation
captureIq()
CaptureMetadata pupradar::RadarSession::captureIq (const CaptureConfig & cfg, const IqSink & sink)
Bulk-read IQ for cfg.duration_s seconds, sinking bytes to sink.
Bulk-reads raw IQ data from EP6 for cfg.duration_s seconds, forwarding each chunk to sink.
Fills out the metadata struct. Does NOT include parsing of the byte stream — capture-only MVP.
Buffer sizing mirrors the GUI at line 2730: (kNumSweepsPerRead=64 + 40) sweeps worth of raw bytes, rounded up to a 512-byte boundary, plus 4096 bytes of padding. The capture loop runs until std::chrono::steady_clock exceeds the computed deadline; zero-length reads are silently skipped. No DSP is performed — this is a capture-only MVP.
Parameters
cfg Capture configuration used for buffer sizing, run duration, and bulk timeout. Must match the configuration previously sent via configure().
sink Callback invoked with each non-empty bulk read chunk (raw pointer into an internal buffer, valid only for the duration of the call).
Returns
CaptureMetadata populated with echoed config values, derived sample rate (fs_hz), sweep time, actual capture duration, byte and read counts, last board info words, firmware path, and a UTC ISO-8601 timestamp.
Exceptions
std::runtime_error on a USB error during bulk transfer (propagated from bulkRead).
Definition at line 283 of file RadarSession.cpp.
References pupradar::CaptureMetadata::actual_duration_s, pupradar::CaptureMetadata::board_info_words, pupradar::CaptureConfig::bulk_timeout_ms, pupradar::CaptureMetadata::bytes_captured, pupradar::CaptureConfig::duration_s, pupradar::CaptureConfig::f_high_hz, pupradar::CaptureMetadata::f_high_hz, pupradar::CaptureConfig::f_low_hz, pupradar::CaptureMetadata::f_low_hz, pupradar::CaptureMetadata::firmware_path, pupradar::CaptureMetadata::fs_hz, fw_path_, pupradar::kEpInBulk, last_board_info_, pupradar::CaptureMetadata::num_rx, pupradar::CaptureMetadata::num_tx, pupradar::CaptureMetadata::reads_completed, pupradar::CaptureMetadata::requested_duration_s, pupradar::CaptureConfig::rx_mask, pupradar::CaptureMetadata::rx_mask, pupradar::rxCount(), pupradar::CaptureConfig::samp_num_idx, pupradar::CaptureMetadata::samples_per_sweep_per_rx, pupradar::samplesPerSweep(), pupradar::CaptureConfig::sweep_time_idx, pupradar::CaptureMetadata::sweep_time_s, pupradar::sweepTimeFromIndex(), pupradar::CaptureMetadata::timestamp_utc, pupradar::CaptureConfig::tx_mask, pupradar::CaptureMetadata::tx_mask, pupradar::txCount(), and usb_.
Referenced by main().
configure()
void pupradar::RadarSession::configure (const CaptureConfig & cfg)
Apply a configuration: send modulation/sweep/sampling/Tx/Rx and PLL regs.
Pushes a full set of FMCW parameters to the radar over USB.
Sends commands in the same order as the MATLAB GUI (SetActiveParameters → Send_Basic_Parameter → Send_PLL_Sawtooth): modulation, sweep time index, sampling number index, Tx mask, Rx mask, then all PLL register bytes for the sawtooth ramp.
Parameters
cfg Capture configuration describing the desired waveform. The MVP requires cfg.modulation == Modulation::Sawtooth; CW is deferred.
Exceptions
std::invalid_argument if cfg.modulation is not Modulation::Sawtooth.
std::runtime_error on any USB write failure (propagated from sendCommand).
Definition at line 240 of file RadarSession.cpp.
References pupradar::buildSawtoothPllCommands(), pupradar::CaptureConfig::f_high_hz, pupradar::CaptureConfig::f_low_hz, pupradar::opcode::kModulation, pupradar::opcode::kRxMask, pupradar::opcode::kSamplingNumIndex, pupradar::opcode::kSweepTimeIndex, pupradar::opcode::kTxMask, pupradar::CaptureConfig::modulation, pupradar::CaptureConfig::rx_mask, pupradar::CaptureConfig::samp_num_idx, pupradar::Sawtooth, sendCommand(), pupradar::CaptureConfig::sweep_time_idx, and pupradar::CaptureConfig::tx_mask.
Referenced by main().
downloadFirmware()
void pupradar::RadarSession::downloadFirmware () private
Downloads the Intel HEX firmware image into FX3 RAM via the Cypress 0xA0 loader protocol.
Sequence mirrors usbdownload.cpp:
Read CPUCS register (0xE600), set bit 0 to hold the 8051 in reset.
Write each HEX data record to its target address via control transfers.
Clear CPUCS bit 0 to release reset — the 8051 begins executing firmware.
After this returns the chip re-enumerates under a new VID/PID. Callers must invoke IUsbBackend::reopenAfterRenumeration() before issuing any further transfers.
Exceptions
std::runtime_error if the HEX file contains no data records or if any control transfer completes with fewer bytes than expected.
Definition at line 99 of file RadarSession.cpp.
References fw_path_, pupradar::kCpucsRegister, pupradar::kCpucsReset, pupradar::kFwLoaderRequest, pupradar::parseIntelHexFile(), and usb_.
Referenced by initialize().
initialize()
void pupradar::RadarSession::initialize (const std::vector< IUsbBackend::VidPid > & post_fw_candidates, unsigned int reenum_timeout_ms = 5000)
Full bring-up: enumerate (pre-firmware), claim, download firmware, wait for re-enumeration, claim again, request board info.
Full device bring-up: open pre-firmware device, download firmware, wait for re-enumeration, reclaim the interface, and fetch board info.
Parameters
post_fw_candidates List of (vid,pid) the chip may take after firmware load. Throws UsbError or std::runtime_error on failure.
Mirrors PUPradar_initiating() in the MATLAB GUI. Steps:
Open the unprogrammed FX2LP (VID 0x04B4 / PID 0x8613).
Claim interface 0, set alternate setting 1 (benign if the descriptor lacks it).
Download firmware via the Cypress 0xA0 loader (downloadFirmware()).
Wait for the chip to re-enumerate under one of post_fw_candidates.
Claim interface 0 and set alternate setting 1 again (now required for bulk EPs).
Request board info (requestBoardInfo()) — result available via lastBoardInfo().
Parameters
post_fw_candidates Non-empty list of (VID, PID) pairs the chip may present after the firmware boots. Tried in order until one opens or the timeout elapses.
reenum_timeout_ms Maximum time in milliseconds to wait for re-enumeration (default: 5000 ms).
Exceptions
std::invalid_argument if post_fw_candidates is empty.
UsbError or std::runtime_error on any USB failure.
Definition at line 196 of file RadarSession.cpp.
References downloadFirmware(), pupradar::kAlternateSetting, pupradar::kInterfaceNumber, pupradar::kPreFirmwarePid, pupradar::kPreFirmwareVid, requestBoardInfo(), and usb_.
Referenced by main().
lastBoardInfo()
const std::vector< std::uint16_t > & pupradar::RadarSession::lastBoardInfo () const inline
For testing / observability.
Definition at line 77 of file RadarSession.hpp.
References last_board_info_.
Referenced by main().
requestBoardInfo()
void pupradar::RadarSession::requestBoardInfo () private
Sends the 0xFA board-info request and parses the response into last_board_info_.
Mirrors the GUI at line 2674: sends opcode kBoardInfoRequest, bulk-reads kBoardInfoReadBytes (512 + 2048) bytes from EP6, then extracts up to kBoardInfoExposedBytes starting at kBoardInfoUsefulOffsetBytes (2048), decoded as little-endian uint16 words.
Hardware note: the device may return fewer than kBoardInfoReadBytes bytes. The observed minimum is ~2058 (useful_offset + 10), which covers all 5 semantically meaningful words from the MATLAB GUI (lines 2675-2683). The decode is therefore bounded by however many bytes actually arrived, not by the nominal kBoardInfoExposedBytes.
Exceptions
std::runtime_error if the bulk read returns fewer than kBoardInfoUsefulOffsetBytes + 2 bytes (less than 1 uint16 word).
Definition at line 152 of file RadarSession.cpp.
References pupradar::opcode::kBoardInfoRequest, pupradar::kEpInBulk, last_board_info_, sendCommand(), and usb_.
Referenced by initialize().
sendCommand()
void pupradar::RadarSession::sendCommand (std::uint8_t opcode, std::uint8_t parameter) private
Packs an opcode/parameter pair into a 512-byte bulk-OUT packet and sends it to EP2.
The MCU interprets only the first 16-bit little-endian word (opcode | param << 8), but the full 512-byte max-packet must be sent to avoid FX2LP framing issues observed on some hosts.
Parameters
opcode Command opcode byte (see pupradar::opcode namespace in Protocol.hpp).
parameter Command parameter byte (semantics depend on opcode).
Exceptions
std::runtime_error if fewer bytes than the full 512-byte packet are transferred.
Definition at line 74 of file RadarSession.cpp.
References pupradar::kEpOutBulk, pupradar::makeCommandPacket(), and usb_.
Referenced by configure(), and requestBoardInfo().
shutdown()
void pupradar::RadarSession::shutdown ()
Power-down convenience: release interfaces, close device.
Releases all USB interfaces and closes the device handle.
After this call the RadarSession is not usable again without a fresh call to initialize().
Definition at line 355 of file RadarSession.cpp.
References usb_.
Referenced by main().
Member Data Documentation
fw_path_
std::string pupradar::RadarSession::fw_path_ private
Definition at line 85 of file RadarSession.hpp.
Referenced by captureIq(), downloadFirmware(), and RadarSession().
last_board_info_
std::vector<std::uint16_t> pupradar::RadarSession::last_board_info_ private
Definition at line 86 of file RadarSession.hpp.
Referenced by captureIq(), lastBoardInfo(), and requestBoardInfo().
usb_
IUsbBackend& pupradar::RadarSession::usb_ private
Definition at line 84 of file RadarSession.hpp.
Referenced by captureIq(), downloadFirmware(), initialize(), RadarSession(), requestBoardInfo(), sendCommand(), and shutdown().
The documentation for this class was generated from the following files:
include/pupradar/RadarSession.hpp
src/RadarSession.cpp