pupradar_capture: pupradar Namespace Reference
pupradar Namespace Reference
Minimal Intel HEX parser, scoped to what the FX2LP firmware loader needs.
Namespaces
namespace opcode
namespace test
Classes
struct BoardInfo
Board-info fields decoded from the 0xFA response (GUI lines 2675-2699).
struct CaptureConfig
struct CaptureMetadata
struct HexRecord
class IqWriter
class IUsbBackend
struct PllCommand
Sawtooth FMCW PLL register pack — given low/high frequency in Hz and sweep-time index, produces the ordered list of opcode/byte pairs that need to be sent in the same order as the MATLAB Send_PLL_Sawtooth function.
class RadarSession
class UsbDevice
class UsbError
Typedefs
using IqSink = std::function<void(const std::uint8_t* data, std::size_t length)>
Enumerations
enum class Modulation : std::uint8_t { Sawtooth = 0 , CW = 3 }
Functions
std::vector< HexRecord > parseIntelHex (std::istream &input)
Parses a stream of Intel HEX text and returns all data records (type 00) in file order.
std::vector< HexRecord > parseIntelHexFile (const std::string &path)
Convenience wrapper that opens a file and parses it.
std::string serializeMetadataJson (const CaptureMetadata &md)
Exposed for unit tests: serialize metadata as JSON into a string.
std::array< std::uint8_t, kBulkOutPacketBytes > makeCommandPacket (std::uint8_t opcode, std::uint8_t parameter)
Build a single 512-byte bulk-OUT packet that the MCU will interpret.
std::array< std::uint8_t, kBulkOutPacketBytes > boardInfoPacket ()
Convenience overload: build the board-info request packet.
std::vector< PllCommand > buildSawtoothPllCommands (double f_low_hz, double f_high_hz, int sweep_time_index)
double sweepTimeFromIndex (int index_1_5)
Translate sweep-time and sampling-number indices to physical values, mirroring SetActiveParameters() in the GUI (lines 1982..2253).
int samplesPerSweep (int sweep_time_idx, int sn_idx, int num_rx)
int txCount (std::uint8_t tx_mask)
int rxCount (std::uint8_t rx_mask)
BoardInfo decodeBoardInfo (const std::vector< std::uint16_t > &words)
Decode a raw board-info word vector (as returned by RadarSession::lastBoardInfo()) into a BoardInfo struct.
Variables
constexpr std::uint16_t kPreFirmwareVid = 0x04B4
constexpr std::uint16_t kPreFirmwarePid = 0x8613
constexpr std::uint8_t kEpOutBulk = 0x02
constexpr std::uint8_t kEpInBulk = 0x86
constexpr std::size_t kBulkOutPacketBytes = 512
constexpr int kInterfaceNumber = 0
constexpr int kAlternateSetting = 1
constexpr std::uint8_t kFwLoaderRequest = 0xA0
constexpr std::uint16_t kCpucsRegister = 0xE600
constexpr std::uint8_t kCpucsReset = 0x01
Detailed Description
Minimal Intel HEX parser, scoped to what the FX2LP firmware loader needs.
Wire protocol constants for the PUP EN24C T2R4 radar.
Abstract USB backend.
Writes raw IQ stream to <out>.bin and metadata to <out>.json.
Supports record types 00 (data), 01 (EOF). Other types (02 ext segment, 03 start segment, 04 ext linear, 05 start linear) are accepted-and-skipped because the FX2LP 8051 firmware fits inside a single 16-bit address space and never uses them. We validate the per-record checksum.
The JSON writer is hand-rolled (~50 lines) — no external dep.
The libusb implementation lives in UsbDevice.cpp; tests substitute FakeUsbBackend (in tests/FakeUsbBackend.hpp).
Designing this interface around the operations the radar driver actually performs (control transfer, bulk read/write, claim, set-alt, reopen) rather than wrapping libusb verbatim keeps tests focused on radar logic instead of USB-stack mechanics.
All values cross-checked against Mex src/*.cpp and Matlab src/PUPradarGUI.m.
Typedef Documentation
IqSink
using pupradar::IqSink = std::function<void(const std::uint8_t* data, std::size_t length)>
Definition at line 52 of file RadarSession.hpp.
Enumeration Type Documentation
Modulation
enum class pupradar::Modulation : std::uint8_t strong
Enumerator
Sawtooth
CW
Definition at line 46 of file Protocol.hpp.
Function Documentation
boardInfoPacket()
std::array< std::uint8_t, kBulkOutPacketBytes > pupradar::boardInfoPacket () inline
Convenience overload: build the board-info request packet.
Definition at line 60 of file Protocol.hpp.
References pupradar::opcode::kBoardInfoRequest, and makeCommandPacket().
buildSawtoothPllCommands()
std::vector< PllCommand > pupradar::buildSawtoothPllCommands (double f_low_hz, double f_high_hz, int sweep_time_index)
Definition at line 84 of file Protocol.cpp.
References pupradar::opcode::kPll03H, pupradar::opcode::kPll03L, pupradar::opcode::kPll03M, pupradar::opcode::kPll04H, pupradar::opcode::kPll04L, pupradar::opcode::kPll04M, pupradar::opcode::kPll0AH, pupradar::opcode::kPll0AL, pupradar::opcode::kPll0AM, pupradar::opcode::kPll0CH, pupradar::opcode::kPll0CL, pupradar::opcode::kPll0CM, pupradar::opcode::kPll0DH, pupradar::opcode::kPll0DL, pupradar::opcode::kPll0DM, pupradar::opcode::kPllSweepStopH, pupradar::opcode::kPllSweepStopL, and sweepTimeFromIndex().
Referenced by pupradar::RadarSession::configure().
decodeBoardInfo()
BoardInfo pupradar::decodeBoardInfo (const std::vector< std::uint16_t > & words)
Decode a raw board-info word vector (as returned by RadarSession::lastBoardInfo()) into a BoardInfo struct.
Returns BoardInfo{valid=false} if the FA05 signature is absent or fewer than 4 words are present.
Definition at line 172 of file Protocol.cpp.
References pupradar::BoardInfo::antenna_type, pupradar::BoardInfo::freq_band, pupradar::BoardInfo::model_name, pupradar::BoardInfo::modelcode, pupradar::BoardInfo::num_rx, pupradar::BoardInfo::num_tx, pupradar::BoardInfo::valid, and pupradar::BoardInfo::version.
Referenced by main().
makeCommandPacket()
std::array< std::uint8_t, kBulkOutPacketBytes > pupradar::makeCommandPacket (std::uint8_t opcode, std::uint8_t parameter)
Build a single 512-byte bulk-OUT packet that the MCU will interpret.
The MCU reads only the first uint16 (little-endian); we still send a full max-packet because the hardware MEX did, and short writes have historically caused FX2LP framing trouble on some hosts.
Definition at line 10 of file Protocol.cpp.
References kBulkOutPacketBytes.
Referenced by boardInfoPacket(), and pupradar::RadarSession::sendCommand().
parseIntelHex()
std::vector< HexRecord > pupradar::parseIntelHex (std::istream & input)
Parses a stream of Intel HEX text and returns all data records (type 00) in file order.
Throws std::runtime_error on:
missing leading ':'
non-hex character
byte-count mismatch
checksum failure
unknown record type other than 00/01/02/03/04/05
missing EOF record (type 01)
Definition at line 27 of file IntelHex.cpp.
References pupradar::HexRecord::address, and pupradar::HexRecord::data.
Referenced by parseIntelHexFile().
parseIntelHexFile()
std::vector< HexRecord > pupradar::parseIntelHexFile (const std::string & path)
Convenience wrapper that opens a file and parses it.
Definition at line 114 of file IntelHex.cpp.
References parseIntelHex().
Referenced by pupradar::RadarSession::downloadFirmware().
rxCount()
int pupradar::rxCount (std::uint8_t rx_mask)
Definition at line 72 of file Protocol.cpp.
Referenced by pupradar::RadarSession::captureIq().
samplesPerSweep()
int pupradar::samplesPerSweep (int sweep_time_idx, int sn_idx, int num_rx)
Definition at line 54 of file Protocol.cpp.
Referenced by pupradar::RadarSession::captureIq().
serializeMetadataJson()
std::string pupradar::serializeMetadataJson (const CaptureMetadata & md)
Exposed for unit tests: serialize metadata as JSON into a string.
Definition at line 41 of file IqWriter.cpp.
References pupradar::CaptureMetadata::actual_duration_s, pupradar::CaptureMetadata::board_info_words, pupradar::CaptureMetadata::bytes_captured, pupradar::CaptureMetadata::f_high_hz, pupradar::CaptureMetadata::f_low_hz, pupradar::CaptureMetadata::firmware_path, pupradar::CaptureMetadata::fs_hz, pupradar::CaptureMetadata::num_rx, pupradar::CaptureMetadata::num_tx, pupradar::CaptureMetadata::reads_completed, pupradar::CaptureMetadata::requested_duration_s, pupradar::CaptureMetadata::rx_mask, pupradar::CaptureMetadata::samples_per_sweep_per_rx, pupradar::CaptureMetadata::sweep_time_s, pupradar::CaptureMetadata::timestamp_utc, and pupradar::CaptureMetadata::tx_mask.
Referenced by pupradar::IqWriter::finalize().
sweepTimeFromIndex()
double pupradar::sweepTimeFromIndex (int index_1_5)
Translate sweep-time and sampling-number indices to physical values, mirroring SetActiveParameters() in the GUI (lines 1982..2253).
Returns seconds.
Definition at line 21 of file Protocol.cpp.
Referenced by buildSawtoothPllCommands(), and pupradar::RadarSession::captureIq().
txCount()
int pupradar::txCount (std::uint8_t tx_mask)
Definition at line 63 of file Protocol.cpp.
Referenced by pupradar::RadarSession::captureIq().
Variable Documentation
kAlternateSetting
int pupradar::kAlternateSetting = 1 constexpr
Definition at line 21 of file Protocol.hpp.
Referenced by pupradar::RadarSession::initialize().
kBulkOutPacketBytes
std::size_t pupradar::kBulkOutPacketBytes = 512 constexpr
Definition at line 19 of file Protocol.hpp.
Referenced by makeCommandPacket().
kCpucsRegister
std::uint16_t pupradar::kCpucsRegister = 0xE600 constexpr
Definition at line 25 of file Protocol.hpp.
Referenced by pupradar::RadarSession::downloadFirmware().
kCpucsReset
std::uint8_t pupradar::kCpucsReset = 0x01 constexpr
Definition at line 26 of file Protocol.hpp.
Referenced by pupradar::RadarSession::downloadFirmware().
kEpInBulk
std::uint8_t pupradar::kEpInBulk = 0x86 constexpr
Definition at line 18 of file Protocol.hpp.
Referenced by pupradar::RadarSession::captureIq(), and pupradar::RadarSession::requestBoardInfo().
kEpOutBulk
std::uint8_t pupradar::kEpOutBulk = 0x02 constexpr
Definition at line 17 of file Protocol.hpp.
Referenced by pupradar::RadarSession::sendCommand().
kFwLoaderRequest
std::uint8_t pupradar::kFwLoaderRequest = 0xA0 constexpr
Definition at line 24 of file Protocol.hpp.
Referenced by pupradar::RadarSession::downloadFirmware().
kInterfaceNumber
int pupradar::kInterfaceNumber = 0 constexpr
Definition at line 20 of file Protocol.hpp.
Referenced by pupradar::RadarSession::initialize().
kPreFirmwarePid
std::uint16_t pupradar::kPreFirmwarePid = 0x8613 constexpr
Definition at line 14 of file Protocol.hpp.
Referenced by pupradar::RadarSession::initialize(), and main().
kPreFirmwareVid
std::uint16_t pupradar::kPreFirmwareVid = 0x04B4 constexpr
Definition at line 13 of file Protocol.hpp.
Referenced by pupradar::RadarSession::initialize(), and main().