pupradar_capture: pupradar::test Namespace Reference
pupradar::test Namespace Reference
Classes
class AssertionError
class FakeUsbBackend
struct Registrar
struct TestCase
struct UsbEvent
Functions
std::vector< TestCase > & registry ()
int runAll ()
Function Documentation
registry()
std::vector< TestCase > & pupradar::test::registry () inline
Definition at line 18 of file test_framework.hpp.
Referenced by pupradar::test::Registrar::Registrar(), and runAll().
runAll()
int pupradar::test::runAll () inline
Definition at line 34 of file test_framework.hpp.
References registry().
Referenced by main().